services:
  db_test:
    image: postgres:16
    container_name: ghosts-auth-db-test
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña
      POSTGRES_DB: nombre_basedatos_test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usuario -d nombre_basedatos_test"]
      interval: 5s
      timeout: 5s
      retries: 10

  app_test:
    container_name: ghosts-auth-api-test
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_USER: usuario
      DATABASE_PASSWORD: contraseña
      DATABASE_HOST: db_test
      DATABASE_PORT: 5432
      DATABASE_NAME: nombre_basedatos_test
      SECRET_KEY: 72942250
      ALLOWED_COUNTRIES: USA,Mexico,Canada,Spain,France
      MAX_ADDRESSES_PER_USER: 5
    depends_on:
      db_test:
        condition: service_healthy
    command: >
      sh -c "pytest --cache-clear"